name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Update every midnight
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: czarekmilek
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_sections: most-used
          plugin_languages_details: percentage