name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Update every midnight
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Languages Card
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          base: "" # Removes the header/avatar to save space
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_sections: most-used

      # Activity/Repo Card
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          base: "" 
          plugin_recent: yes
          plugin_recent_limit: 4
          plugin_repositories: yes
          plugin_repositories_pinned: 3
