name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Update every midnight
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: czarekmilek
          template: classic
          base: header # Basic info (name, etc.)
          config_timezone: Europe/Warsaw
          
          # 1. LANGUAGES
          plugin_languages: yes
          plugin_languages_details: percentage
          
          # 2. FEATURED REPOS
          plugin_repositories: yes
          plugin_repositories_pinned: 4
          
          # 3. LAST ACTIVITY
          plugin_recent: yes
          plugin_recent_sections: last
          plugin_recent_limit: 5
